// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.2.2

package querytest

import (
	"encoding/json"
)

type Transaction struct {
	ID        int64
	Uri       string
	ProgramID string
	Data      json.RawMessage
}
