// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.1.0

package querytest

import (
	"database/sql"
)

type Author struct {
	ID          int64
	Name        string
	Bio         sql.NullString
	CountryCode string
	Titles      []string
}

type Client struct {
	ID   int32
	Name string
}
