// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.2.1

package override

type Bar struct {
	ID      string `type:"id" utype:"nullable_text"`
	OtherID string `type:"other_id" utype:"nullable_text"`
	About   string `utype:"nullable_text"`
	Other   string `type:"other" utype:"nullable_text"`
}

type Foo struct {
	ID          string `source:"foo" type:"id" utype:"nullable_text"`
	OtherID     string `type:"other_id" utype:"nullable_text"`
	About       string `type:"about" utype:"nullable_text"`
	Other       string `type:"this" utype:"nullable_text"`
	Notnulltext string `utype:"notnull_text"`
}
