// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.1.0

package db

import (
	"database/sql"
)

type Routergroup struct {
	Groupid                int32
	Groupname              string
	Defaultconfigid        sql.NullInt32
	Defaultfirmwareversion sql.NullString
	Parentgroupid          sql.NullInt32
	Firmwarepolicy         sql.NullString
	Styles                 sql.NullString
}
