// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v1.31.1

package querytest

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Order struct {
	ID           int64
	Quantity     pgtype.Numeric
	OrderCatalog pgtype.Int4
}
