// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v1.31.1
// source: query.sql

package querytest

import (
	"context"
)

const sumOrder = `-- name: SumOrder :one
SELECT SUM(quantity) FROM orders
`

func (q *Queries) SumOrder(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, sumOrder)
	var sum int64
	err := row.Scan(&sum)
	return sum, err
}
