// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.2.1

package querytest

import (
	"database/sql"
)

type Foo struct {
	Bar sql.NullString
	Bat string
	Baz sql.NullInt64
	Qux int64
}
