// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.2.1

package querytest

import (
	"time"
)

type Author struct {
	Name      string
	DeletedAt time.Time
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Book struct {
	IsAmazing bool
	DeletedAt time.Time
	CreatedAt time.Time
	UpdatedAt time.Time
}
