// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.1.0
// source: query.sql

package querytest

import (
	"context"
)

const deleteAuthor = `-- name: DeleteAuthor :exec
UPDATE
  authors,
  books
SET
  authors.deleted_at = now(),
  books.deleted_at = now()
WHERE
  books.is_amazing = 1
  AND authors.name = ?
`

func (q *Queries) DeleteAuthor(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteAuthor, name)
	return err
}
