// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.2.1

package querytest

import (
	"database/sql"
)

type Arena struct {
	Name sql.NullString
}

type Location struct {
	Name sql.NullString
}
