// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.2.2
// source: query.sql

package querytest

import (
	"context"
	"encoding/json"
)

const bulkInsert = `-- name: BulkInsert :copyfrom
INSERT INTO foo (a, b) VALUES (?, ?)
`

type BulkInsertParams struct {
	A json.RawMessage
	B json.RawMessage
}

const selectFoo = `-- name: SelectFoo :exec
SELECT a, b FROM foo
`

func (q *Queries) SelectFoo(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, selectFoo)
	return err
}
