// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.1.0

package querytest

type Change struct {
	Ranked int32
}

type ChangesRanked struct {
	Ranked                 int32
	RankByEffectSize       int32
	RankByAbsPercentChange int32
}
