// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v1.31.1

package querytest

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type GroupedKpi struct {
	Day   pgtype.Interval
	Count int64
}

type Kpi struct {
	Ts      pgtype.Timestamptz
	EventID string
}
