// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v1.31.1
// source: query.sql

package querytest

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getTotalEarned = `-- name: GetTotalEarned :one
SELECT COALESCE(SUM(earned), 0) as total_earned
FROM grouped_kpis
WHERE day = $1
`

func (q *Queries) GetTotalEarned(ctx context.Context, day pgtype.Interval) (interface{}, error) {
	row := q.db.QueryRow(ctx, getTotalEarned, day)
	var total_earned interface{}
	err := row.Scan(&total_earned)
	return total_earned, err
}
