// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v1.31.1

package querytest

type A struct {
	ID int64
	A  string
}

type B struct {
	ID  int64
	B   string
	AID int64
}

type C struct {
	ID  int64
	C   string
	AID int64
}

type D struct {
	ID  int64
	D   string
	AID int64
}

type E struct {
	ID  int64
	E   string
	AID int64
}
