// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.2.2

package querytest

import (
	"database/sql"
)

type Author struct {
	ID   int32
	Name string
	Bio  sql.NullString
}

type Book1 struct {
	AuthorID int32
	Name     sql.NullString
}

type Book2 struct {
	AuthorID int32
	Name     sql.NullString
}
