// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.1.0
// source: query.sql

package querytest

import (
	"context"
)

const getAuthors = `-- name: GetAuthors :many
SELECT id, name, bio FROM authors
WHERE author_id IN (SELECT author_id FROM book1 UNION SELECT author_id FROM book2)
`

func (q *Queries) GetAuthors(ctx context.Context) ([]Author, error) {
	rows, err := q.db.QueryContext(ctx, getAuthors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Author
	for rows.Next() {
		var i Author
		if err := rows.Scan(&i.ID, &i.Name, &i.Bio); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
