// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.1.0

package querytest

type Location struct {
	ID        int64
	Name      string
	Address   string
	ZipCode   int64
	Latitude  float64
	Longitude float64
}
