// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v1.31.1

package db

import (
	"github.com/sqlc-dev/sqlc-testdata/pkg"
)

type Override struct {
	ONE   pkg.CustomType
	Two   int64
	Three pkg.CustomType
	Four  []byte
	Five  []pkg.CustomType
}
