// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v0.1.0

package querytest

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Employee struct {
	ID      int64
	Name    string
	Manager pgtype.Text
}
