// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.1.0

package override

import (
	t "github.com/jackc/pgtype"
)

type Foo struct {
	Other   string
	Total   int64
	Retyped *t.Text
}
