// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.1.0

package querytest

import (
	"database/sql"
)

type Bar struct {
	ID int64
}

type Foo struct {
	ID  int64
	Bar sql.NullInt64
}
