// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.2.2

package querytest

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type TestTable struct {
	VBitNull    pgtype.Bits
	VVarbitNull pgtype.Bits
	VBit        pgtype.Bits
	VVarbit     pgtype.Bits
}
