// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.2.1

package querytest

import (
	"database/sql"
)

type NewTable struct {
	Val sql.NullInt32
}

type OldTable struct {
	Val sql.NullInt32
}

type PgTempMigrate struct {
	Val sql.NullInt32
}
