// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.1.0

package querytest

type Bar struct {
	ID uint64
}

type Baz struct {
	ID uint64
}

type Foo struct {
	BarID uint64
	BazID int32
}
