// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.1.0

package querytest

import (
	"github.com/jackc/pgtype"
)

type Foo struct {
	Bar pgtype.Text
	Bam pgtype.Name
	Baz pgtype.Name
}
