// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v1.31.1

package dynamicquerysqlite

import (
	"time"
)

type Record struct {
	ID        int64
	TenantID  int64
	Name      string
	Age       int64
	Status    string
	CreatedAt time.Time
}
