// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.2.2
// source: query.sql

package querytest

import (
	"context"
)

const demo = `-- name: Demo :one
SELECT CAST(CHAR(1,2,3,4,5) AS BLOB) AS col1
`

func (q *Queries) Demo(ctx context.Context) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, demo)
	var col1 []byte
	err := row.Scan(&col1)
	return col1, err
}
