// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.2.1

package querytest

type SysAction struct {
	ID        int64
	Code      string
	Menu      string
	Title     string
	Resources []byte
}
