// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.2.1

package querytest

type Bar struct {
	ID int32
}

type Baz struct {
	ID int32
}

type Foo struct {
	BarID int32
	BazID int32
}
