// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.2.1

package querytest

import (
	"database/sql"
	"encoding/json"
)

type Test struct {
	ID sql.NullInt32
	J  json.RawMessage
}
