// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.2.1
// source: query.sql

package querytest

import (
	"database/sql"
)

const insertSingleValue = `-- name: InsertSingleValue :copyfrom
INSERT INTO foo (a) VALUES (?)
`

type InsertSingleValueParams struct {
	A sql.NullString
}
