// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v1.31.1

package querytest

import (
	"database/sql"

	"github.com/sqlc-dev/sqlc-testdata/mysql"
)

type Foo struct {
	ID    int32
	Name  string
	Bar   sql.NullString
	Mystr mysql.ID
}
