// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.1.0

package querytest

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Bar struct {
	A pgtype.Text
	B pgtype.Text
}

type Foo struct {
	A pgtype.Text
	B pgtype.Text
}
