// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.2.1

package querytest

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Article struct {
	ID         int32
	Company    int32
	Name       string
	SortOrder  int32
	ObjectType int16
	Image      pgtype.Text
	Group      pgtype.Int4
	Notes      string
}
