// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v1.31.1
// source: query.sql

package querytest

import (
	"context"
)

const updateArticles = `-- name: UpdateArticles :exec
UPDATE
	public.articles
SET
	is_deleted = TRUE
WHERE
	id = $1
`

func (q *Queries) UpdateArticles(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, updateArticles, id)
	return err
}
