// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.2.2

package querytest

import (
	"github.com/jackc/pgtype"
)

type TestTable struct {
	VBoxNull     pgtype.Box
	VCircleNull  pgtype.Circle
	VLineNull    pgtype.Line
	VLsegNull    pgtype.Lseg
	VPathNull    pgtype.Path
	VPointNull   pgtype.Point
	VPolygonNull pgtype.Polygon
	VBox         pgtype.Box
	VCircle      pgtype.Circle
	VLine        pgtype.Line
	VLseg        pgtype.Lseg
	VPath        pgtype.Path
	VPoint       pgtype.Point
	VPolygon     pgtype.Polygon
}
