// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v1.31.1

package querytest

import (
	"database/sql"
)

type Author struct {
	ID       int64
	Username sql.NullString
	Email    sql.NullString
	Name     string
	Bio      sql.NullString
}
