// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.2.1
// source: query.sql

package querytest

import (
	"context"
)

const schemaScopedUpdate = `-- name: SchemaScopedUpdate :exec
UPDATE foo.bar SET name = ? WHERE id = ?
`

type SchemaScopedUpdateParams struct {
	Name string
	ID   uint64
}

func (q *Queries) SchemaScopedUpdate(ctx context.Context, arg SchemaScopedUpdateParams) error {
	_, err := q.db.ExecContext(ctx, schemaScopedUpdate, arg.Name, arg.ID)
	return err
}
