// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.2.2

package db

import (
	"database/sql"
)

type Author struct {
	ID     int64
	Name   string
	Rating int64
	Score  uint32
	Bio    sql.NullString
}
