// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.1.0

package booktest

import (
	"time"
)

type Author struct {
	AuthorID int64
	Name     string
}

type Book struct {
	BookID    int64
	AuthorID  int64
	Isbn      string
	BookType  string
	Title     string
	Yr        int64
	Available time.Time
	Tag       string
}
