// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.2.1

package querytest

import (
	"database/sql"
)

type Bar struct {
	A     int32
	Alias sql.NullString
}

type Foo struct {
	A    int32
	Name sql.NullString
}
