// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v1.31.1

package db

type JoinTable struct {
	ID             uint64
	PrimaryTableID uint64
	OtherTableID   uint64
	IsActive       bool
}

type PrimaryTable struct {
	ID     uint64
	UserID uint64
}
