// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.1.0

package querytest

import (
	"github.com/jackc/pgtype"
)

type TestTable struct {
	VBitNull    pgtype.Varbit
	VVarbitNull pgtype.Varbit
	VBit        pgtype.Varbit
	VVarbit     pgtype.Varbit
}
