// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.1.0

package querytest

import (
	"database/sql"
)

type FirstView struct {
	Val string
}

type Foo struct {
	Val  string
	Val2 sql.NullInt32
}

type SecondView struct {
	Val  string
	Val2 sql.NullInt32
}
