// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.1.0

package override

type Bar struct {
	Other      string `utype:"notnull_text"`
	AlsoTagged string `also:"tagged" utype:"notnull_text"`
}

type Baz struct {
	Other      string `utype:"notnull_text"`
	AlsoTagged string `also:"tagged" utype:"notnull_text"`
}

type Foo struct {
	Other    string `utype:"notnull_text"`
	Tagged   string `a:"b" utype:"notnull_text" x:"y,z"`
	Nulltext string `utype:"nullable_text"`
}
