// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.2.1

package querytest

import (
	"database/sql"
)

type Author struct {
	ID       int64
	Name     string
	ParentID sql.NullInt64
}
