// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.2.1

package querytest

type Attribute struct {
	ID   int64
	Name string
}

type AttributeValue struct {
	ID        int64
	Val       string
	Attribute int64
}
