// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.2.2

package querytest

import (
	"database/sql"
)

type Author struct {
	ID   int64
	Name sql.NullString
}

type Book struct {
	ID    int64
	Title sql.NullString
}

type User struct {
	ID   int64
	Name sql.NullString
}
