// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v1.31.1

package querytest

import (
	"database/sql"
)

type Ft struct {
	B string
}

type Tbl struct {
	A int64
	B sql.NullString
	C sql.NullString
	D sql.NullString
	E sql.NullInt64
}

type TblFt struct {
	B string
	C string
}
