// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.2.1

package querytest

import (
	"database/sql"
)

type Bar struct {
	A sql.NullString
	B sql.NullString
}

type Foo struct {
	A sql.NullString
	B sql.NullString
}
