// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.2.1

package querytest

import (
	"database/sql"

	"github.com/google/uuid"
)

type Foo struct {
	Description sql.NullString
	Bar         uuid.NullUUID
	Baz         uuid.UUID
}
