// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.1.0

package jets

type Jet struct {
	ID      int32
	PilotID int32
	Age     int32
	Name    string
	Color   string
}

type Language struct {
	ID       int32
	Language string
}

type Pilot struct {
	ID   int32
	Name string
}

type PilotLanguage struct {
	PilotID    int32
	LanguageID int32
}
