// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.2.2

package querytest

import (
	"database/sql"
)

type Author struct {
	ID       int64
	Username interface{}
	Email    interface{}
	Name     string
	Bio      sql.NullString
}
