// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.2.2
// source: query.sql

package db

import (
	"context"
)

const getRestrictedId = `-- name: GetRestrictedId :one
SELECT
  NULLIF(id, $1) restricted_id
FROM
  author
`

func (q *Queries) GetRestrictedId(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getRestrictedId, id)
	var restricted_id int64
	err := row.Scan(&restricted_id)
	return restricted_id, err
}
