// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v1.31.1

package querytest

import (
	"github.com/jackc/pgtype"
)

type Foo struct {
	A pgtype.JSON
	B pgtype.JSONB
	C pgtype.JSON
	D pgtype.JSONB
}
