// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.2.2

package querytest

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Version struct {
	ID                int64
	Name              pgtype.Text
	PreviousVersionID int64
}
