// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.1.0

package querytest

import (
	"encoding/json"
)

type Foo struct {
	A json.RawMessage
	B json.RawMessage
	C json.RawMessage
	D json.RawMessage
	E json.RawMessage
	F json.RawMessage
	G json.RawMessage
	H json.RawMessage
}
