// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v1.31.1
// source: query.sql

package querytest

import (
	"database/sql"
)

const insertMultipleValues = `-- name: InsertMultipleValues :copyfrom
INSERT INTO foo (a, b) VALUES (?, ?)
`

type InsertMultipleValuesParams struct {
	A sql.NullString
	B sql.NullString
}
