// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.2.1
// source: query.sql

package querytest

import (
	"context"
)

const insertBar = `-- name: InsertBar :execlastid
INSERT INTO bar () VALUES ()
`

func (q *Queries) InsertBar(ctx context.Context) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertBar)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}
