// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v1.31.1

package querytest

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Foo struct {
	QualifiedName pgtype.Text
	NameQuery     pgtype.Text
	FtsNameQuery  pgtype.Text
}
