// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.1.0

package querytest

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID        int32       `db:"id"`
	FirstName string      `db:"first_name"`
	LastName  pgtype.Text `db:"last_name"`
	Age       int32       `db:"age"`
}
