// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v1.31.1

package querytest

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID        int32
	FirstName string
	LastName  pgtype.Text
	Age       int32
}
