// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.2.2

package querytest

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type L struct {
	ID       int64
	ParentID pgtype.Int4
}

type T struct {
	ID  int64
	LID pgtype.Int4
	F   pgtype.Text
}
