// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.2.1

package querytest

import (
	"database/sql"
)

type Bar struct {
	ID int32
}

type Foo struct {
	ID  int32
	Bar sql.NullInt32
}
