// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.2.1

package querytest

import (
	"database/sql"
	"time"
)

type Notice struct {
	ID        int32
	Cnt       int32
	Status    string
	NoticeAt  sql.NullTime
	CreatedAt time.Time
}
