// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.1.0

package querytest

import (
	"database/sql"
)

type Authors1 struct {
	ID   int64
	Name string
	Bio  sql.NullString
}

type Authors2 struct {
	ID   int64
	Name string
	Bio  sql.NullString
}

type Authors3 struct {
	ID   int64
	Name string
	Bio  sql.NullString
}

type Authors4 struct {
	ID   int64
	Name string
	Bio  sql.NullString
}
