// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.2.1
// source: query.sql

package querytest

import (
	"context"
)

const getAuthor = `-- name: GetAuthor :one
SELECT id, name, bio FROM authors1
WHERE id = ?1 LIMIT 1
`

func (q *Queries) GetAuthor(ctx context.Context, id int64) (Authors1, error) {
	row := q.db.QueryRowContext(ctx, getAuthor, id)
	var i Authors1
	err := row.Scan(&i.ID, &i.Name, &i.Bio)
	return i, err
}
