// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.2.1

package querytest

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type TddTest struct {
	TestID    pgtype.UUID
	Title     string
	Descr     string
	TsCreated pgtype.Timestamptz
	TsUpdated pgtype.Timestamptz
}
