// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v1.31.1

package querytest

type Bar struct {
	ID int32
}

type Baz struct {
	ID int32
}

type Foo struct {
	BarID int32
	BazID int32
}
