// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.2.1

package db

import (
	"time"

	"github.com/google/uuid"
)

type Foo struct {
	Time  time.Time
	Time2 time.Time
	Uuid  uuid.UUID
	Uuid2 uuid.UUID
}
