// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.1.0

package querytest

import (
	"database/sql"
)

type Foo struct {
	A sql.NullString
	B sql.NullInt32
	C sql.NullTime
	D sql.NullTime
}
