// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.2.2

package querytest

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AstoriaSlackFeedback struct {
	ID          int64
	WorkspaceID int64
	CreatedAt   pgtype.Timestamp
	IssueRaised pgtype.Bool
}

type AstoriaTicket struct {
	ID          int64
	WorkspaceID int64
	CreatedAt   pgtype.Timestamp
	Source      string
}
