// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.2.2
// source: query.sql

package querytest

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const badQuery = `-- name: BadQuery :exec
WITH
	q
		AS (
			SELECT
				authors.name, authors.bio
			FROM
				authors
				LEFT JOIN fake ON authors.name = fake.name
		)
SELECT
	name, bio
FROM
	q AS c1
WHERE c1.name = $1
`

func (q *Queries) BadQuery(ctx context.Context, dollar_1 pgtype.Text) error {
	_, err := q.db.Exec(ctx, badQuery, dollar_1)
	return err
}
