// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v1.31.1

package querytest

type Author struct {
	ID   uint32
	Name string
}

type AuthorBook struct {
	AuthorID uint32
	BookID   uint32
}

type Book struct {
	ID    uint32
	Title string
}
