// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.1.0

package querytest

import (
	"time"

	"github.com/google/uuid"
)

type TddTest struct {
	TestID    uuid.UUID
	Title     string
	Descr     string
	TsCreated time.Time
	TsUpdated time.Time
}
