// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.2.2

package querytest

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type SolarCommcardMapping struct {
	ID        int64
	DeviceId  int64
	Version   string
	Sn        string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
