// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.2.1
// source: query.sql

package querytest

import (
	"context"
)

const truncate = `-- name: Truncate :exec
TRUNCATE bar
`

func (q *Queries) Truncate(ctx context.Context) error {
	_, err := q.db.Exec(ctx, truncate)
	return err
}
