// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.1.0

package querytest

import (
	"context"
)

type Querier interface {
	CreateAuthors(ctx context.Context, authorID []int32) (int64, error)
}

var _ Querier = (*Queries)(nil)
