// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.1.0

package db

import (
	"database/sql"
)

type X struct {
	A sql.NullString
	B sql.NullString
}

type Y struct {
	A sql.NullString
	B sql.NullString
}
