// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.2.2

package querytest

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Bar struct {
	ColA pgtype.Bool
	ColB pgtype.Bool
}

type Foo struct {
	ColA bool
	ColB bool
}
