// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.2.1
// source: query.sql

package querytest

import (
	"context"
)

const createFoo = `-- name: CreateFoo :exec
INSERT INTO foo (id) VALUES (?)
`

func (q *Queries) CreateFoo(ctx context.Context, id uint32) error {
	_, err := q.db.ExecContext(ctx, createFoo, id)
	return err
}
