// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.2.1

package querytest

import (
	"database/sql"
)

type Bar struct {
	ID    uint64
	Title sql.NullString
}

type Foo struct {
	ID uint64
}
