// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.2.2

package querytest

import (
	"github.com/pgvector/pgvector-go"
)

type Item struct {
	ID        int64
	Embedding pgvector.Vector
}
