// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.2.2

package dynamicquerypgx

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Record struct {
	ID        int64
	TenantID  int64
	Name      string
	Age       int32
	Status    string
	CreatedAt pgtype.Timestamptz
}
