// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.2.1
// source: query.sql

package querytest

import (
	"context"
)

const schemaScopedDelete = `-- name: SchemaScopedDelete :exec
DELETE FROM foo.bar WHERE id = $1
`

func (q *Queries) SchemaScopedDelete(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, schemaScopedDelete, id)
	return err
}
