// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.2.2

package querytest

import (
	"context"
)

type Querier interface {
	User(ctx context.Context) ([]int64, error)
}

var _ Querier = (*Queries)(nil)
