// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.2.1

package querytest

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Author struct {
	ID     int64
	Name   string
	Bio    pgtype.Text
	Gender pgtype.Int4
}

type AuthorsName struct {
	Name string
}
