// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.2.2
// source: query.sql

package querytest

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type InsertValuesParams struct {
	A pgtype.Text
	B pgtype.Int4
}
