// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.2.2

package querytest

import (
	"database/sql"
)

type User struct {
	ID           int64
	FullName     sql.NullString
	EmailAddress sql.NullString
	CreatedAt    sql.NullString
}
