// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v1.31.1

package querytest

import (
	"context"
)

type Querier interface {
	GetValues(ctx context.Context) ([]GetValuesRow, error)
}

var _ Querier = (*Queries)(nil)
