// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.2.1

package querytest

import (
	"database/sql"
)

type Foo struct {
	QualifiedName sql.NullString
	NameQuery     sql.NullString
	FtsNameQuery  sql.NullString
}
