// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.1.0

package datatype

import (
	"time"
)

type DtType struct {
	A *int64
	B *float64
	C *bool
	D *time.Time
	E *string
	F *float64
}

type DtTypesNotNull struct {
	A int64
	B float64
	C bool
	D time.Time
	E string
	F float64
}
