// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.2.1
// source: query.sql

package querytest

import (
	"database/sql"
)

type InsertValuesParams struct {
	A sql.NullString
	B sql.NullInt32
}
