// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v1.31.1

package querytest

import (
	"database/sql"
)

type Foo struct {
	Bar    string
	Baz    sql.NullInt32
	Bio    sql.NullInt32
	Foobar []int32
}
