// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.2.1

package querytest

import (
	"database/sql"
)

type User struct {
	ID        int64
	FirstName string
	LastName  sql.NullString
	Age       int64
}
