// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.1.0

package querytest

import (
	"database/sql"
)

type Venue struct {
	Name     sql.NullString
	Location sql.NullString
	Size     sql.NullInt64
}
