// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.2.1

package querytest

type Bar struct {
	ID int64
}

type Baz struct {
	ID int64
}

type Foo struct {
	BarID int64
	BazID int64
}
