// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.2.1

package querytest

import (
	"database/sql"
)

type Arena struct {
	Name     string
	Location sql.NullString
	Size     int64
}
