// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v1.31.1

package querytest

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	FirstName pgtype.Text `json:"first_name"`
	LastName  pgtype.Text `json:"last_name"`
	Age       pgtype.Int2 `json:"age"`
}
