// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.2.2
// source: query.sql

package querytest

import (
	"context"
)

const updateSetMultiple = `-- name: UpdateSetMultiple :exec
UPDATE foo SET name = ?, slug = ?
`

type UpdateSetMultipleParams struct {
	Name string
	Slug string
}

func (q *Queries) UpdateSetMultiple(ctx context.Context, arg UpdateSetMultipleParams) error {
	_, err := q.db.ExecContext(ctx, updateSetMultiple, arg.Name, arg.Slug)
	return err
}
