// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.1.0
// source: sqlite.query.sql

package db

import (
	"context"
)

const createTable = `-- name: CreateTable :exec
CREATE TABLE test (id INTEGER NOT NULL)
`

func (q *Queries) CreateTable(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, createTable)
	return err
}
