// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v1.31.1
// source: query.sql

package querytest

import (
	"context"
)

const placeholder = `-- name: Placeholder :exec
SELECT 1
`

func (q *Queries) Placeholder(ctx context.Context) error {
	_, err := q.db.Exec(ctx, placeholder)
	return err
}
