// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.2.2

package querytest

type Item struct {
	ItemID int64
}

type Plan struct {
	PlanID int64
}

type PlanItem struct {
	PlanItemID int64
	PlanID     int64
	ItemID     int64
}
