// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v1.31.1
// source: query.sql

package querytest

import (
	"context"
)

const getDate = `-- name: GetDate :one
SELECT now from NOW()
`

func (q *Queries) GetDate(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRow(ctx, getDate)
	var now interface{}
	err := row.Scan(&now)
	return now, err
}
