// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.2.1

package db

import (
	"context"

	models "github.com/theoriginalstove/dsqlsea/endtoend/output_models_path/postgresql/model"
)

type Querier interface {
	CreateAuthor(ctx context.Context, arg CreateAuthorParams) (models.Author, error)
	GetAuthor(ctx context.Context, id int64) (models.Author, error)
	GetBook(ctx context.Context, id int64) (models.Book, error)
	ListAuthors(ctx context.Context) ([]models.Author, error)
	ListAuthorsByStatus(ctx context.Context, status models.Status) ([]models.Author, error)
}

var _ Querier = (*Queries)(nil)
