// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.2.2
// source: query.sql

package querytest

import (
	"context"
	"database/sql"
)

const insertContact = `-- name: InsertContact :exec
INSERT INTO contacts (
    pid,
    CustomerName
)
VALUES (?,?)
`

type InsertContactParams struct {
	Pid          sql.NullString
	Customername sql.NullString
}

func (q *Queries) InsertContact(ctx context.Context, arg InsertContactParams) error {
	_, err := q.db.ExecContext(ctx, insertContact, arg.Pid, arg.Customername)
	return err
}
