// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v1.31.1

package querytest

import (
	"database/sql"
	"time"
)

type Measurement struct {
	CityID    int32
	Logdate   time.Time
	Peaktemp  sql.NullInt32
	Unitsales sql.NullInt32
}

type MeasurementY2006m02 struct {
	CityID    int32
	Logdate   time.Time
	Peaktemp  sql.NullInt32
	Unitsales sql.NullInt32
}
