// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.1.0
// source: query.sql

package querytest

import (
	"context"
)

const aliasBar = `-- name: AliasBar :exec
DELETE FROM bar AS b
WHERE b.id = ?
`

func (q *Queries) AliasBar(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, aliasBar, id)
	return err
}
