// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.1.0

package querytest

import (
	"database/sql"
)

type Bar struct {
	ID                     int32
	NobodyWouldBelieveThis sql.NullInt32
	ParentID               sql.NullInt32
}
