// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.2.1

package querytest

import (
	"database/sql"
)

type Event struct {
	ID sql.NullInt32
}

type HandledEvent struct {
	LastHandledID sql.NullInt32
	Handler       sql.NullString
}
