// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.1.0

package querytest

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Foo struct {
	Bar    string
	Baz    pgtype.Int4
	Bio    pgtype.Int4
	Foobar []int32
}
