// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.1.0

package querytest

import (
	"database/sql"
)

type Author struct {
	Name string
	Bio  sql.NullString
}

type Person struct {
	FirstName string
}
