// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.2.2

package querytest

import (
	"database/sql"
)

type User struct {
	FirstName sql.NullString `json:"FirstName"`
	LastName  sql.NullString `json:"LastName"`
	Age       sql.NullInt16  `json:"Age"`
}
