// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.2.1

package querytest

import (
	"time"
)

type User struct {
	ID        int32
	Fname     string
	Lname     string
	Email     string
	EncPasswd string
	CreatedAt time.Time
}
