// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.1.0
// source: query.sql

package querytest

import (
	"context"
)

const barExists = `-- name: BarExists :one
SELECT
    EXISTS (
        SELECT
            1
        FROM
            bar
        where
            id = ?
    )
`

func (q *Queries) BarExists(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRowContext(ctx, barExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
