// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v1.31.1
// source: query.sql

package querytest

import (
	"context"
)

const insertWorkspace = `-- name: InsertWorkspace :exec
INSERT INTO workspace DEFAULT VALUES
`

func (q *Queries) InsertWorkspace(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, insertWorkspace)
	return err
}
