// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v1.31.1

package querytest

import (
	"database/sql"
)

type User struct {
	ID        int64          `db:"id" json:"id"`
	FirstName string         `db:"first_name" json:"first_name"`
	LastName  sql.NullString `db:"last_name" json:"last_name"`
	Age       int64          `db:"age" json:"age"`
}
