// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.1.0
// source: query.sql

package querytest

import (
	"context"
)

const barNotExists = `-- name: BarNotExists :one
SELECT
    NOT EXISTS (
        SELECT
            1
        FROM
            bar
        WHERE
            id = ?
    )
`

func (q *Queries) BarNotExists(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRowContext(ctx, barNotExists, id)
	var not_exists bool
	err := row.Scan(&not_exists)
	return not_exists, err
}
