// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v1.31.1

package querytest

import (
	"context"
)

type Querier interface {
	DeleteBarByID(ctx context.Context, id int32) (int64, error)
}

var _ Querier = (*Queries)(nil)
