// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.2.1

package querytest

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Dict struct {
	ID         string
	AppID      string
	Code       pgtype.Text
	ParentCode string
	Label      string
	Value      pgtype.Text
	Weight     int32
	IsDefault  bool
	IsVirtual  bool
	Status     int16
	CreateAt   pgtype.Timestamptz
	CreateBy   string
	UpdateAt   pgtype.Timestamptz
	UpdateBy   pgtype.Text
	IsDelete   bool
}
