// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v1.31.1

package querytest

import (
	"database/sql"
)

type User struct {
	ID        uint64
	FirstName string
	LastName  sql.NullString
}
