// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v1.31.1

package querytest

import (
	"database/sql"
)

type Bar struct {
	ID    int32
	Title sql.NullString
}

type Foo struct {
	ID int32
}
