// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.1.0

package db

type JoinTable struct {
	ID             int32
	PrimaryTableID int32
	OtherTableID   int32
	IsActive       bool
}

type PrimaryTable struct {
	ID     int32
	UserID int32
}
