// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.1.0

package querytest

import (
	"database/sql"
)

type User struct {
	ID        int32
	FirstName string
	LastName  sql.NullString
	Age       int32
}
