// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.2.1

package db

import (
	"database/sql"
)

type Bar struct {
	ColA sql.NullBool
	ColB sql.NullBool
	ColC sql.NullBool
}

type Foo struct {
	ColA bool
	ColB bool
	ColC bool
}
