// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.2.1

package querytest

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Memory struct {
	ID        uuid.UUID
	VampireID uuid.UUID
	CreatedAt time.Time
	UpdatedAt sql.NullTime
}

type Vampire struct {
	ID uuid.UUID
}
