// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.2.1

package querytest

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateMemories(ctx context.Context, vampireID []uuid.UUID) ([]Memory, error)
	GetVampireIDs(ctx context.Context, vampireID []uuid.UUID) ([]uuid.UUID, error)
}

var _ Querier = (*Queries)(nil)
