// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.2.2

package dynamicquery

import (
	"database/sql"
	"time"
)

type Profile struct {
	ID        int64
	RecordID  int64
	Bio       sql.NullString
	AvatarUrl sql.NullString
	CreatedAt time.Time
}

type Record struct {
	ID        int64
	TenantID  int64
	Name      string
	Age       int32
	Status    string
	CreatedAt time.Time
}

type RecordTag struct {
	RecordID int64
	TagID    int64
}

type Tag struct {
	ID   int64
	Name string
}
