// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.2.1
// source: query.sql

package db

import (
	"context"
)

const updateAuthor = `-- name: UpdateAuthor :exec
UPDATE authors
SET name = $1
WHERE id = $1
`

func (q *Queries) UpdateAuthor(ctx context.Context, name bool) error {
	_, err := q.db.Exec(ctx, updateAuthor, name)
	return err
}
