// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.2.2

package querytest

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CaseIntent struct {
	ID               int32
	CaseIntentString string
	Description      string
	Author           string
}

type CaseIntentParentJoin struct {
	CaseIntentID       int64
	CaseIntentParentID int64
}

type CaseIntentVersion struct {
	VersionID int32
	Reviewer  string
	CreatedAt pgtype.Timestamptz
}

type CaseIntentVersionJoin struct {
	CaseIntentID        int64
	CaseIntentVersionID int32
}
