// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.2.1
// source: query.sql

package querytest

import (
	"context"
)

const listFoos = `-- name: ListFoos :one
SELECT id FROM foo WHERE id = frobnicate($1)
`

func (q *Queries) ListFoos(ctx context.Context, frobnicate interface{}) (string, error) {
	row := q.db.QueryRowContext(ctx, listFoos, frobnicate)
	var id string
	err := row.Scan(&id)
	return id, err
}
