// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.1.0
// source: query.sql

package querytest

import (
	"context"
)

const selectOne = `-- name: SelectOne :one
SELECT 1
`

func (q *Queries) SelectOne(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, selectOne)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}
