// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.2.2

package querytest

import (
	"database/sql"
)

type Author struct {
	ID       int32
	Name     string
	ParentID sql.NullInt32
}
