// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.2.2
// source: query.sql

package querytest

import (
	"context"
)

const getAuthorMv = `-- name: GetAuthorMv :one
SELECT id, name, bio FROM authors_mv
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetAuthorMv(ctx context.Context, id int64) (AuthorsMv, error) {
	row := q.db.QueryRow(ctx, getAuthorMv, id)
	var i AuthorsMv
	err := row.Scan(&i.ID, &i.Name, &i.Bio)
	return i, err
}
