// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.1.0
// source: query.sql

package querytest

import (
	"context"
)

const starExpansionReserved = `-- name: StarExpansionReserved :many
SELECT "group", key FROM foo
`

func (q *Queries) StarExpansionReserved(ctx context.Context) ([]Foo, error) {
	rows, err := q.db.Query(ctx, starExpansionReserved)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Foo
	for rows.Next() {
		var i Foo
		if err := rows.Scan(&i.Group, &i.Key); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
