// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.1.0

package querytest

import (
	"github.com/google/uuid"
)

type Foo struct {
	ID      uuid.UUID
	OtherID uuid.UUID
}

type Foo1 struct {
	ID      uuid.UUID
	OtherID uuid.UUID
}
