// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v1.31.1

package querytest

import (
	"database/sql"
)

type Author struct {
	ID   int64
	Name string
	Age  sql.NullInt64
}

type Book struct {
	ID         int64
	Author     string
	Translator string
	Year       sql.NullInt64
}

type Translator struct {
	ID   int64
	Name string
	Age  sql.NullInt64
}
