// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.2.1

package db

import (
	"context"
)

type Querier interface {
	GetAll(ctx context.Context) ([]int32, error)
}

var _ Querier = (*Queries)(nil)
