// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.1.0

package querytest

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type NewTable struct {
	Val pgtype.Int4
}

type OldTable struct {
	Val pgtype.Int4
}

type PgTempMigrate struct {
	Val pgtype.Int4
}
