// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.1.0

package querytest

import (
	"database/sql"
)

// Table comment
type Bar struct {
	// Column comment
	Baz sql.NullString
}
