// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.1.0

package ondeck

import (
	"database/sql"
	"time"
)

type City struct {
	Slug string `json:"slug"`
	Name string `json:"name"`
}

type Venue struct {
	ID              int64          `json:"id"`
	Status          string         `json:"status"`
	Statuses        sql.NullString `json:"statuses"`
	Slug            string         `json:"slug"`
	Name            string         `json:"name"`
	City            string         `json:"city"`
	SpotifyPlaylist string         `json:"spotify_playlist"`
	SongkickID      sql.NullString `json:"songkick_id"`
	Tags            sql.NullString `json:"tags"`
	CreatedAt       time.Time      `json:"created_at"`
}
