// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.2.2

package querytest

import (
	"context"
)

type Querier interface {
	Bar(ctx context.Context) error
	Bars(ctx context.Context) error
}

var _ Querier = (*Queries)(nil)
