// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v1.31.1

package querytest

import (
	"database/sql"
)

type Bar struct {
	ColA sql.NullBool
	ColB sql.NullBool
}

type Foo struct {
	ColA bool
	ColB bool
}
