// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.2.1

package override

type Foo struct {
	ID          string `utype:"nullable_text" x:"y"`
	OtherID     string `utype:"nullable_text"`
	Notnulltext string `utype:"notnull_text"`
}
