// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.2.1

package primary_key_later

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Author struct {
	ID   int64
	Name string
	Bio  pgtype.Text
}
