// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.2.1
// source: query.sql

package db

import (
	"context"
)

const runVetAll = `-- name: RunVetAll :exec
SELECT true
`

func (q *Queries) RunVetAll(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, runVetAll)
	return err
}

const skipVetAll = `-- name: SkipVetAll :exec
SELECT true
`

// @sqlc-vet-disable
func (q *Queries) SkipVetAll(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, skipVetAll)
	return err
}

const skipVetInvalidRule = `-- name: SkipVetInvalidRule :exec
SELECT true
`

// @sqlc-vet-disable always-fail
// @sqlc-vet-disable block-delete
// @sqlc-vet-disable no-exec
func (q *Queries) SkipVetInvalidRule(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, skipVetInvalidRule)
	return err
}

const skipVetMultiLine = `-- name: SkipVetMultiLine :exec
SELECT true
`

// @sqlc-vet-disable always-fail
// @sqlc-vet-disable no-exec
func (q *Queries) SkipVetMultiLine(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, skipVetMultiLine)
	return err
}

const skipVetSingleLine = `-- name: SkipVetSingleLine :exec
SELECT true
`

// @sqlc-vet-disable always-fail no-exec
func (q *Queries) SkipVetSingleLine(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, skipVetSingleLine)
	return err
}

const skipVet_always_fail = `-- name: SkipVet_always_fail :exec
SELECT true
`

// @sqlc-vet-disable always-fail
func (q *Queries) SkipVet_always_fail(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, skipVet_always_fail)
	return err
}

const skipVet_no_exec = `-- name: SkipVet_no_exec :exec
SELECT true
`

// @sqlc-vet-disable no-exec
func (q *Queries) SkipVet_no_exec(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, skipVet_no_exec)
	return err
}
