// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.1.0

package querytest

import (
	"database/sql"
)

type Bar struct {
	C sql.NullString
	D sql.NullString
}

type Foo struct {
	A sql.NullString
	B sql.NullString
}
