// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.2.1

package querytest

import (
	"database/sql"
)

type Customer struct {
	CustID   int64
	CustName sql.NullString
	CustAddr sql.NullString
}

type CustomerAddress struct {
	CustID   int64
	CustAddr sql.NullString
}

type TriggerCustomer struct {
	Name    string
	Address sql.NullString
}

type TriggerOrder struct {
	ID           int64
	CustomerName sql.NullString
	Address      sql.NullString
}
