// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.2.2
// source: query.sql

package db

import (
	"context"
	"database/sql"
)

const selectFoo = `-- name: SelectFoo :many
SELECT bar_id FROM foo
`

func (q *Queries) SelectFoo(ctx context.Context) ([]sql.NullString, error) {
	rows, err := q.db.QueryContext(ctx, selectFoo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []sql.NullString
	for rows.Next() {
		var bar_id sql.NullString
		if err := rows.Scan(&bar_id); err != nil {
			return nil, err
		}
		items = append(items, bar_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
