// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.2.2

package date_and_time_functions

import (
	"database/sql"
)

type Student struct {
	StudentName sql.NullString
	TestScore   sql.NullFloat64
}
