// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.1.0

package querytest

type Calorie struct {
	ID string
}

type Campus struct {
	ID string
}

type ProductMetadatum struct {
	ID string
}

type ProductMetum struct {
	ID string
}

type Student struct {
	ID string
}
