// Code generated by dsqlsea. DO NOT EDIT.
// versions:
//   dsqlsea v0.2.1

package querytest

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Order struct {
	ID     int32
	Price  pgtype.Numeric
	UserID int32
}

type User struct {
	ID        int32
	FirstName string
	LastName  pgtype.Text
	Age       int32
	JobStatus string
}
